#AntTweakBar (without X11 support)
ATB_STATIC := /home/kdl/projects/anttweakbar/atb_osx_lean/lib/atb.a
ATB_INCLUDE:= /home/kdl/projects/anttweakbar/atb_osx_lean/include

#GLFW; includes use GL/glfw.h, which is default on linux.
GLFW_STATIC:= /usr/lib/libglfw.a
GLFW_INCLUDE:= /usr/include

#GTEST
GTEST_STATIC:=/home/kdl/projects/gtest/gtest/lib/.libs/libgtest_main.a /home/kdl/projects/gtest/gtest/lib/.libs/libgtest.a 
GTEST_INCLUDE:=/home/kdl/projects/gtest/gtest/include

#FTGL
FTGL_STATIC:=/home/kdl/lib/libftgl.a
FTGL_INCLUDE:=/home/kdl/include

LINKFLAGS := -lGL -lGLU -lXrandr -lm -lz
CXXFLAGS := -DLINUX

ETAGSFLAGS := --declarations

-include Makefile